# HW 1: Julia (Solution)
---
`ISE 754, Fall 2024`

__Assigned:__ Wed, 21 Aug (Individual Assignment)  
__Due:__ 10:00a, Wed, 28 Aug 

Please use the Code cells in this Jupyter Notebook to answer the following questions. Please run all of the cells in your notebook and then submit it as a .ipynb file, along with a .html or .pdf copy, via Moodle. (There is a _Run All Cells_ command under the _Run_ menu.)

---

__(1)__ Given the array `x = [3, 1, 2, 9, 5, 4]`, provide the single command  (namely, one line of code with at most one assignment (i.e., one equals sign =)) needed to perform the following actions. Unless noted, all of the actions should not modify `x`; instead, the result of the action will just be displayed in the notebook. If `x` is modified, type `x` on a second line in the cell to display the modified `x` in full (otherwise, just the modified elements of `x` will be displayed; the modified `x` should be used for subsequent actions.

(a) After first creating `x`, extract the third element from `x`

In [1]:
x = [3, 1, 2, 9, 5, 4]
x[3]

2

(b) Extract all but the last element from `x`

In [2]:
x[1:end-1]

5-element Vector{Int64}:
 3
 1
 2
 9
 5

(c) Extract the first, third, first, sixth, and first element from `x`

In [3]:
x[[1, 3, 1, 6, 1]]

5-element Vector{Int64}:
 3
 2
 3
 4
 3

(d) Reverse the elements of `x`

In [4]:
reverse(x)    # 1st approach

6-element Vector{Int64}:
 4
 5
 9
 2
 1
 3

In [5]:
x[end:-1:1]    # second approach

6-element Vector{Int64}:
 4
 5
 9
 2
 1
 3

(e) Calculate the sum of all of the elements of `x`

In [6]:
sum(x)

24

(f) Calculate the sum from the first to the _i_ th element of `x`, for all elements 1 to _i_ in `x`

In [7]:
cumsum(x)    # 1st approach

6-element Vector{Int64}:
  3
  4
  6
 15
 20
 24

In [8]:
[sum(x[1:i]) for i in 1:length(x)]    # 2nd approach

6-element Vector{Int64}:
  3
  4
  6
 15
 20
 24

(g) Modify `x` by setting the second and sixth elements of `x` equal to zero; then type `x` on a second line in cell in order to display the result

In [9]:
x[[2, 6]] .= 0
x

6-element Vector{Int64}:
 3
 0
 2
 9
 5
 0

(h) Using the result from (g), modify `x` by deleting its third element

In [10]:
deleteat!(x,3)
x

5-element Vector{Int64}:
 3
 0
 9
 5
 0

(i) Using the result from (h), modify `x` by adding 7 to its end

In [11]:
push!(x,7)
x

6-element Vector{Int64}:
 3
 0
 9
 5
 0
 7

---
__(2)__ Provide a single command needed to create or modify the following arrays:

(a) A two-row, three-column matrix consisting of all integer zero values

In [12]:
zeros(Int, 2,3)

2×3 Matrix{Int64}:
 0  0  0
 0  0  0

(b) A 3-element array whose first element is the vector `[1, 4, 2]`, second element is the matrix `[2 5 4; 1 8 3]`, and third element is the scalar 6.5

In [13]:
[[1, 4, 2], [2 5 4; 1 8 3], 6.5]

3-element Vector{Any}:
  [1, 4, 2]
  [2 5 4; 1 8 3]
 6.5

(c) Multiply each element of the array from (b) by 2

In [14]:
[2x for x  in [[1, 4, 2], [2 5 4; 1 8 3], 6.5]]

3-element Vector{Any}:
   [2, 8, 4]
   [4 10 8; 2 16 6]
 13.0

---
__(3)__ A chemical processing facility will operate 24 hours a day, seven days a week. As a byproduct of its operation, hazardous waste material is generated at a constant rate of 1 ton per day and will be stored until removal. The facility has contracted to have its hazardous waste removed three times per week. The truck that will be used has the capacity to remove up to 15 tons of material, but no other details regarding the contract are currently available. Estimate how many tons, on average, of the hazardous material will be in storage at the facility.

In [15]:
@show tLB = 7/3          # Perfect control
tUB = 7                  # Bad control
@show t = sqrt(tLB*tUB)  # Time between removals (day)
r = 1                    # Waste rate (ton/day)
q = r * t/2              # Average waste in storage (ton)
println("Average waste in storage (ton) = ", q)

tLB = 7 / 3 = 2.3333333333333335
t = sqrt(tLB * tUB) = 4.041451884327381
Average waste in storage (ton) = 2.0207259421636903


__Note:__ _ISE754 GPT_ gave $q = r * tLB/2 = 1.165$ tons as estimate

---
__(4)__ Create a function `d1` that determines the rectilinear distance between two points:

$ d = \lvert x_1 - x_2 \rvert + \lvert y_1 - y_2 \rvert $ 

In [16]:
d1(x1, x2) = length(x1) == length(x2) ? sum(abs.(x1 .- x2)) : 
    error("Inputs not same length.")

x1 = (3, 1)
x2 = (6, 5)
d1(x1, x2)

7

---
__(5)__ Create a function `sum_d2` that returns the sum of the Euclidean distances between a single point and multiple other points.

In [17]:
d2(x1, x2) = length(x1) == length(x2) ? sqrt(sum((x1 .- x2).^2)) : 
    error("Inputs not same length.")
sum_d2(x, pt) = sum(d2.([xy], pt))

pt = [(1, 1), (6, 1), (6, 5)]
xy = (3, 1)
sum_d2(xy, pt)

10.0